// <auto-generated />
using _24SevenOfficeForum.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace _24SevenOfficeForum.Migrations
{
    [DbContext(typeof(_24hOfficeforumContext))]
    [Migration("20180430082507_FullViewModel")]
    partial class FullViewModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_24SevenOfficeForum.Models.Answer", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Body")
                        .IsUnicode(false);

                    b.Property<int?>("Upvote");

                    b.HasKey("Id");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("_24SevenOfficeForum.Models.Category", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("CategoryName")
                        .IsUnicode(false);

                    b.Property<string>("Description")
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("_24SevenOfficeForum.Models.FullViewModel", b =>
                {
                    b.Property<int>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Identifier");

                    b.ToTable("FullViewModels");
                });

            modelBuilder.Entity("_24SevenOfficeForum.Models.Question", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Body")
                        .IsUnicode(false);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Header")
                        .IsUnicode(false);

                    b.Property<int?>("QuestionId");

                    b.Property<int?>("Upvote");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("_24SevenOfficeForum.Models.Question", b =>
                {
                    b.HasOne("_24SevenOfficeForum.Models.Answer", "QuestionNavigation")
                        .WithMany("Question")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK_Question_Answer");
                });
#pragma warning restore 612, 618
        }
    }
}
